/*
 * @Author: Young 
 * @Date: 2019-04-26 10:02:43 
 * @Last Modified by: Young
 * @Last Modified time: 2019-04-28 17:57:31
 */

export const HOMEPAGE_SHOWSEARCHBAR = 'HOMEPAGE/SHOWSEARCHBAR';

export const HOMEPAGE_FETCH = 'HOMEPAGE/FETCH';

export const HOMEPAGE_FETCH_SEARCHBAR = 'HOMEPAGE/FETCH/SEARCHBAR';

export const HOMEPAGE_FETCH_SUCCESS = 'HOMEPAGE/FETCH/SUCCESS';

export const HOMEPAGE_FETCH_FAIL = 'HOMEPAGE/FETCH/FAIL';

export const HOMEPAGE_MENU_PAGECHANGE = 'HOMEPAGE/MENU/PAGECHANGE';

export const HOMEPAGE_GRID_FETCH = 'HOMEPAGE/GRID/FETCH';

// export const HOMEPAGE_GRID_FETCH_FULFILLED = 'HOMEPAGE/GRID/FETCH/FULFILLED';
